name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0" # Updated SDK range to match the latest Flutter versions.

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^13.0.2
  http: ^1.2.2
  flutter_spinkit: ^5.2.1

  cupertino_icons: ^1.0.5 # Updated to the latest version.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Added Flutter lints for better coding standards.

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900